// Get all bookings
GET http://localhost:8080/bookings
Authorization: Bearer {{jwt}}

###

// Get one specific booking
GET http://localhost:8080/bookings/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}

###

// Create a new booking
POST http://localhost:8080/bookings/
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Jessy Jones",
  "booking_type": "AFTERNOON",
  "status": "PENDING"
}

###

// Update one specific booking
PUT http://localhost:8080/bookings/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}

{
  "name": "Mark Whalberg",
  "id": "e1eec954-6ef4-4926-8183-7575af189f2a",
  "booking_type": "MORNING",
  "status": "PENDING",
}

###

// Delete one specific and existing booking
DELETE http://localhost:8080/bookings/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}