// Get all bookings
GET http://localhost:8080/bookings
Authorization: Bearer {{jwt}}

###

// Get one specific booking
GET http://localhost:8080/bookings/b8160463-01a0-4c7a-bd46-5b3716dbe4c6
Authorization: Bearer {{jwt}}

###

// Create a new booking
POST http://localhost:8080/bookings
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "id": "69d61dd9-4a1c-49b1-8804-e0e2ee10e423",
    "name": "Jessy Jones",
    "booking_type": "AFTERNOON",
    "status": "PENDING"
}

###

// Approve a new booking
PUT http://localhost:8080/bookings/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "id": "413e2297-b84b-42ef-97ed-16a8a9d1d671",
    "name": "Andreas Seidl",
    "booking_type": "DAY",
    "status": "APPROVED"
}

###

// Deny a new booking
PUT http://localhost:8080/bookings/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "id": "413e2297-b84b-42ef-97ed-16a8a9d1d671",
    "name": "Andreas Seidl",
    "booking_type": "DAY",
    "status": "DENIED"
}

###

// Update one specific booking
PUT http://localhost:8080/bookings/b8160463-01a0-4c7a-bd46-5b3716dbe4c6
Authorization: Bearer {{jwt}}

{
  "name": "Mark Whalberg",
  "id": "e1eec954-6ef4-4926-8183-7575af189f2a",
  "booking_type": "MORNING",
  "status": "PENDING",
}

###

// Delete one specific and existing booking
DELETE http://localhost:8080/bookings/b8160463-01a0-4c7a-bd46-5b3716dbe4c6
Authorization: Bearer {{jwt}}

###

// List all members
GET http://localhost:8080/member
Authorization: Bearer {{jwt}}

###

// Delete one specific and existing Member
DELETE http://localhost:8080/member/f6b24684-fff3-456d-bba7-fb6b376d678f
Authorization: Bearer {{jwt}}
