// Get all bookings
GET http://localhost:8080/bookings
Authorization: Bearer {{jwt}}

###

// Get one specific booking
GET http://localhost:8080/bookings/b8160463-01a0-4c7a-bd46-5b3716dbe4c6
Authorization: Bearer {{jwt}}

###

// Create a new booking
POST http://localhost:8080/bookings
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Jessy Jones",
  "booking_type": "AFTERNOON",
  "status": "PENDING"
}

###

// Update one specific booking
PUT http://localhost:8080/bookings/b8160463-01a0-4c7a-bd46-5b3716dbe4c6
Authorization: Bearer {{jwt}}

{
  "name": "Mark Whalberg",
  "id": "e1eec954-6ef4-4926-8183-7575af189f2a",
  "booking_type": "MORNING",
  "status": "PENDING",
}

###

// Delete one specific and existing booking
DELETE http://localhost:8080/bookings/b8160463-01a0-4c7a-bd46-5b3716dbe4c6
Authorization: Bearer {{jwt}}

###

// List all members
GET http://localhost:8080/member
Authorization: Bearer {{jwt}}
